# Generated by Django 5.0.1 on 2026-02-23 23:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackendEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_date', models.DateField(db_index=True, editable=False)),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('agent_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('agent_session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('path', models.TextField(db_index=True)),
                ('method', models.CharField(max_length=20)),
                ('status_code', models.PositiveIntegerField()),
                ('latency_ms', models.FloatField()),
                ('request_size_bytes', models.PositiveIntegerField(default=0)),
                ('response_size_bytes', models.PositiveIntegerField(default=0)),
                ('request_headers', models.TextField(blank=True, null=True)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('query_params', models.TextField(blank=True, null=True)),
                ('post_data', models.TextField(blank=True, null=True)),
                ('response_headers', models.TextField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('request_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('response_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_properties', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'backend_event',
                'indexes': [models.Index(fields=['project_id'], name='backend_eve_project_2fd6d4_idx'), models.Index(fields=['agent_id'], name='backend_eve_agent_i_8a5da8_idx'), models.Index(fields=['agent_session_id'], name='backend_eve_agent_s_dbac23_idx'), models.Index(fields=['path'], name='backend_eve_path_6a48b8_idx'), models.Index(fields=['event_date'], name='backend_eve_event_d_10dd9b_idx')],
            },
        ),
    ]
