# Generated by Django 5.0.1 on 2026-02-22 02:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to='users.user')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='BackendAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(db_index=True, max_length=255)),
                ('hashed_key', models.TextField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='projects.project')),
            ],
            options={
                'db_table': 'backend_api_keys',
            },
        ),
        migrations.CreateModel(
            name='UserProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Member')], default=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_mappings', to='users.user')),
            ],
            options={
                'db_table': 'user_project_mapping',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='project_created_86fac0_idx'),
        ),
        migrations.AddIndex(
            model_name='backendapikey',
            index=models.Index(fields=['project_id'], name='backend_api_project_b7df13_idx'),
        ),
        migrations.AddIndex(
            model_name='backendapikey',
            index=models.Index(fields=['prefix'], name='backend_api_prefix_28808f_idx'),
        ),
        migrations.AddIndex(
            model_name='backendapikey',
            index=models.Index(fields=['active'], name='backend_api_active_8a1b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprojectmapping',
            index=models.Index(fields=['user'], name='user_projec_user_id_701466_idx'),
        ),
        migrations.AddIndex(
            model_name='userprojectmapping',
            index=models.Index(fields=['project'], name='user_projec_project_9860f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userprojectmapping',
            unique_together={('user', 'project')},
        ),
    ]
