# Generated by Django 5.0.1 on 2026-02-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sdk_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
