# Generated by Django 5.0.1 on 2026-02-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.URLField(blank=True, null=True),
        ),
    ]
