# Generated by Django 5.0.1 on 2026-02-15 06:59

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_sdk_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sdk_key',
            field=models.CharField(default=projects.models.generate_sdk_key, editable=False, max_length=64, unique=True),
        ),
    ]
