# Generated by Django 5.0.1 on 2026-02-18 06:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_sdk_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('provider', models.TextField(blank=True, db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_agents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='projects.project')),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='AgentKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(db_index=True, max_length=255)),
                ('hashed_key', models.TextField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='agents.agent')),
            ],
            options={
                'db_table': 'agent_key',
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='agents.agent')),
                ('agent_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='agents.agentkey')),
            ],
            options={
                'db_table': 'agent_session',
            },
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['project_id'], name='agent_project_92fb6e_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['provider'], name='agent_provide_72ac7c_idx'),
        ),
        migrations.AddIndex(
            model_name='agentkey',
            index=models.Index(fields=['agent_id'], name='agent_key_agent_i_925b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='agentkey',
            index=models.Index(fields=['prefix'], name='agent_key_prefix_372fee_idx'),
        ),
        migrations.AddIndex(
            model_name='agentkey',
            index=models.Index(fields=['active'], name='agent_key_active_d167dc_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['agent_id'], name='agent_sessi_agent_i_5abb93_idx'),
        ),
    ]
